FROM node:latest

WORKDIR /usr/src/app/
ENV NODE_ENV development
COPY package.json ./
COPY package-lock.json ./
RUN npm install -g @angular/cli
RUN npm install --silent --no-cache

# COPY ./ ./


# CMD ["npm", "run", "start"]
